config/routes.rb
Datildave::Application.routes.draw do
  
  get 'recipes/new'

  get 'recipes/edit'

  post "product/add_to_cart" => "products#add_to_cart"
  post "cart/empty_cart" => "cart#empty_cart"
  post "order/payment" => "orders#payment"
  get "cart" => "cart#show", as: "cart"
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "contact" => "contact#new", as: :new_contact
  post "contact" => "contact#create", as: :create_contact
  match 'heartbeat', to: proc { [200, {}, ''.chars] }, via: [:get, :post]
  root to: 'home#index'

  resources :sessions
  resources :users
  resources :products
  resources :pages, only: [:new, :create, :index]
  resources :posts
  resources :orders
  resources :categories
  resources :recipes do
    resources :ingredients
  end

  #keep these at the bottom of your file. They should be the last routes.
  get "/:slug", to: "pages#show", as: :slug
  get "/:slug/edit", to: "pages#edit", as: :edit_slug
  put "/:slug", to: "pages#update", as: :update_slug
  delete "/:slug", to: "pages#destroy", as: :destroy_slug

end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessor :stripe_card_token

  validates_presence_of :customer_email, :address_street_1, :address_city, :address_state, :address_zip
  validates_format_of :customer_email, with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  def save_with_payment
    if valid?
      total = (100 * (shipping.to_f + subtotal.to_f)).to_i
      payment_response = Stripe::Charge.create(
        amount: total,
        currency: "usd",
        card: stripe_card_token,
        description: "Charge for #{customer_email}"
      )

      self.stripe_payment_token = payment_response.id
      save!
    end

  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while processing payment: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
  end

  def self.package_products(products)
    tmp = []
    products.each do |item|
      tmp << hash_to_string(item)
    end

    tmp.join("|")
  end

  def self.unpack_products(products)
    tmp = []
    products.split("|").each do |item|
      tmp << string_to_hash(item)
    end

    tmp
  end

  def total
    subtotal.to_f + shipping.to_f
  end

  private
  
  def self.hash_to_string(hsh)
    tst = []
    hsh.each do |key, value| 
      tst << "#{value}@#{key}"
    end

    tst.join(",")
  end

  def self.string_to_hash(str)
    hsh = str.split(",").inject(Hash.new{|h,k| h[k]=""}) do |h,s|
      v, k = s.split(/@/)
      k = k.to_sym
      h[k] = v
      h
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :require_user, only: [:show, :edit, :update, :destroy]

  expose(:pages)
  expose(:orders)
  expose(:order)
  expose(:order_items) {Order.unpack_products(order.products)}

  def new
    @order = order
    @subtotal = 0 
    @shipping = 0
    frozen_products = 0
    unfrozen_products = 0
    session[:cart].each do |item|
      product = Product.find(item[:product_id].to_i)
      @subtotal += item[:product_price].to_f * item[:product_quantity].to_f
      @shipping += item[:shipping].to_f * item[:product_quantity].to_f
      if product.frozen_product == true
        frozen_products += 1 
      else
        unfrozen_products +=1
      end
    end

    @shipping = 12.65 if unfrozen_products > 0 && frozen_products == 0
    @shipping = 17.65 if unfrozen_products == 0 && frozen_products > 0
    @shipping = 30.3 if unfrozen_products > 0 && frozen_products > 0

  end

  def create
    @order = Order.new(order_params)

    @order.products = Order.package_products(session[:cart])

    if @order.save_with_payment
      
      session[:cart].each do |item|
        product = Product.find(item[:product_id])
        new_quantity = product.quantity - item[:product_quantity].to_i

        product.update_attribute(:quantity, new_quantity)
      end

      Contact.new_order_confirmation(@order).deliver_now
      Contact.new_order(@order).deliver_now

      session[:cart] = []
      redirect_to root_path, notice: "Thank you for your order!"
    else
      @subtotal = 0 
      @shipping = 0    
      session[:cart].each do |item|
        @subtotal += item[:product_price].to_f * item[:product_quantity].to_f
        @shipping += item[:shipping].to_f * item[:product_quantity].to_f
      end

      render "new"
    end
  end

  def update
    if order.update_attributes(order_params)
      redirect_to order, notice: "Order updated."
    else
      render 'edit'
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_email, :customer_first_name, :customer_last_name, :address_street_1, :address_street_2, :address_city, :address_state, :address_zip, :processed, :notes, :products, :shipped, :shipping, :subtotal, :stripe_card_token)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.haml
%h1= "Edit Order ##{order.id}"

=form_for order do |f|
  .field
    = f.label :customer_email
    %br
    = f.text_field :customer_email

  .field
    = f.label :customer_first_name
    %br
    = f.text_field :customer_last_name

  .field
    = f.label :address_street_1
    %br
    = f.text_field :address_street_1

  .field
    = f.label :address_street_2
    %br
    = f.text_field :address_street_2

  .field
    = f.label :address_city
    %br
    = f.text_field :address_city

  .field
    = f.label :address_state
    %br
    = f.text_field :address_state
    
  .field
    = f.label :address_zip
    %br
    = f.text_field :address_zip

  .field
    = f.label :processed
    %br
    = f.check_box :processed

  .field
    = f.label :shipped
    %br
    = f.check_box :shipped

  .field
    = f.label :notes
    %br
    = f.text_area :notes

  .field
    = f.submit

app/views/orders/index.html.haml
%h1 Orders
%table.table.table-striped
  %tr
    %th Order #
    %th Date
    %th Customer Email
    %th Subtotal
    %th Processed
    %th Shipped
  - orders.each do |order|
    %tr
      %td= link_to order.id, order
      %td= link_to order.created_at.strftime('%F'), order
      %td= link_to order.customer_email, order
      %td= link_to number_to_currency(order.subtotal), order
      %td= link_to order.processed.to_s, order
      %td= link_to order.shipped.to_s, order

app/views/orders/new.html.haml
.row
  .col-md-9
    %h1 Place Order

.row
  - if @order.errors.any?
    .alert.alert-warning
      = pluralize(@order.errors.count, "error") 
      prohibited this order from being placed:

      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
  .col-md-9
    %table.table
      %tr
        %th Name
        %th Price
        %th Quantity
        %th Subtotal

      - session[:cart].each do |item|
        .col-md-9
          %tr
            %td
              = item[:product_name]
            %td
              = number_to_currency item[:product_price]
            %td
              = item[:product_quantity]
            %td
              = number_to_currency(item[:product_price].to_f * item[:product_quantity].to_f)

.row
  .col-md-3
    %p
      Shipping:
      = number_to_currency @shipping.to_f

.row
  .col-md-3
    %p
      Total:
      = number_to_currency @subtotal + @shipping

.row
  .col-md-9
    = form_for order do |f|
      = f.hidden_field :shipped, value: "false"
      = f.hidden_field :processed, value: "false"
      = f.hidden_field :subtotal, value: @subtotal
      = f.hidden_field :shipping, value: @shipping
      = f.hidden_field :stripe_card_token
      
      %dt
        = f.label :customer_first_name, "First Name"
      %dd
        = f.text_field :customer_first_name

      %dt
        = f.label :customer_last_name, "Last Name"
      %dd
        = f.text_field :customer_last_name
      
      %dt
        = f.label :customer_email, "E-Mail"
      %dd
        = f.text_field :customer_email
     
      %dt
        = f.label :address_street_1, "Street 1"
      %dd
        = f.text_field :address_street_1

      %dt
        = f.label :address_street_2, "Street 2"
      %dd
        = f.text_field :address_street_2

      %dt
        = f.label :address_city, "City"
      %dd
        = f.text_field :address_city

      %dt
        = f.label :address_state, "State"
      %dd
        = f.text_field :address_state, size: "2"

      %dt
        = f.label :address_zip, "Zip"
      %dd
        = f.text_field :address_zip

      %dt
        %label Card Number
      %dd
        %input{type: "text", size: "20", autocomplete: "off", id: "card_number"}

      %dt
        %label CVC
      %dd
        %input{type: "text", size: "4", autocomplete: "off", id: "card_code"}

      %dt
        = label_tag :card_month, "Card Expiration"
      %dd
        = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}
        = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}

      .action
        = f.submit "Place Order"

app/views/orders/show.html.haml
.row
  .col-md-9
    %h1 Order summary:

.row
  .col-md-9
    = link_to "Edit", edit_order_path(order)

.row
  .col-md-9
    %p
      %strong Order Date: 
      = order.created_at.strftime('%F')
    %p
      %strong Customer name: 
      = "#{order.customer_first_name} #{order.customer_last_name}"
    %p
      %strong Customer email: 
      = order.customer_email
    %p 
      %strong Shipping Address:
    %address
      =order.address_street_1
      %br
      -unless order.address_street_2.nil? or order.address_street_2 == ""
        =order.address_street_2
        %br
      = "#{order.address_city}, #{order.address_state} #{order.address_zip}"

    %table.table.table-striped
      %tr
        %th Product
        %th Price
        %th Qty
      - Order.unpack_products(order.products).each do |product|
        %tr
          %td= product[:product_name]
          %td= number_to_currency(product[:product_price].to_f)
          %td= product[:product_quantity]

    %p= "Processed: #{order.processed.to_s}"
    %p= "Shipped: #{order.shipped.to_s}"
    %p= "Stripe Payment Token: #{order.stripe_payment_token}"