config/routes.rb
Datildave::Application.routes.draw do
  
  get 'recipes/new'

  get 'recipes/edit'

  post "product/add_to_cart" => "products#add_to_cart"
  post "cart/empty_cart" => "cart#empty_cart"
  post "order/payment" => "orders#payment"
  get "cart" => "cart#show", as: "cart"
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "contact" => "contact#new", as: :new_contact
  post "contact" => "contact#create", as: :create_contact
  match 'heartbeat', to: proc { [200, {}, ''.chars] }, via: [:get, :post]
  root to: 'home#index'

  resources :sessions
  resources :users
  resources :products
  resources :pages, only: [:new, :create, :index]
  resources :posts
  resources :orders
  resources :categories
  resources :recipes do
    resources :ingredients
  end

  #keep these at the bottom of your file. They should be the last routes.
  get "/:slug", to: "pages#show", as: :slug
  get "/:slug/edit", to: "pages#edit", as: :edit_slug
  put "/:slug", to: "pages#update", as: :update_slug
  delete "/:slug", to: "pages#destroy", as: :destroy_slug

end

app/models/cart.rb
class Cart

  def self.subtotal(args)
    sub = 0
    args.each do |item|
      sub += item[:product_price].to_f * item[:product_quantity].to_f
    end
    return sub
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many(:products)
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/message.rb
class Message
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessor :stripe_card_token

  validates_presence_of :customer_email, :address_street_1, :address_city, :address_state, :address_zip
  validates_format_of :customer_email, with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  def save_with_payment
    if valid?
      total = (100 * (shipping.to_f + subtotal.to_f)).to_i
      payment_response = Stripe::Charge.create(
        amount: total,
        currency: "usd",
        card: stripe_card_token,
        description: "Charge for #{customer_email}"
      )

      self.stripe_payment_token = payment_response.id
      save!
    end

  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while processing payment: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
  end

  def self.package_products(products)
    tmp = []
    products.each do |item|
      tmp << hash_to_string(item)
    end

    tmp.join("|")
  end

  def self.unpack_products(products)
    tmp = []
    products.split("|").each do |item|
      tmp << string_to_hash(item)
    end

    tmp
  end

  def total
    subtotal.to_f + shipping.to_f
  end

  private
  
  def self.hash_to_string(hsh)
    tst = []
    hsh.each do |key, value| 
      tst << "#{value}@#{key}"
    end

    tst.join(",")
  end

  def self.string_to_hash(str)
    hsh = str.split(",").inject(Hash.new{|h,k| h[k]=""}) do |h,s|
      v, k = s.split(/@/)
      k = k.to_sym
      h[k] = v
      h
    end
  end

end

app/models/page.rb
class Page < ActiveRecord::Base

  default_scope { order('created_at DESC, updated_at DESC') }

  validates_uniqueness_of :name

  before_save :update_slug

  def update_slug
    self.slug = name.parameterize
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :category
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: lambda { |a| a[:name].blank? }, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :name

  def self.authenticate (name, password)
    user = find_by_name(name)

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  expose(:pages)
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      Contact.new_message(@message).deliver_now

      redirect_to :root, notice: "Message successfully sent."
    else
      flash.now.alert = "Please fill in all fields correctly."
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(text, path, options={})
    if /^#{url_for(path)}/ =~ request.path
      options[:class] = "#{options[:class]} active"
    end
    link_to text, path, options
  end

  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end

  def new_fields_template(f,association,options={})
    options[:object] ||= f.object.class.reflect_on_association(association).klass.new
    options[:partial] ||= association.to_s.singularize+"_fields"
    options[:template] ||= association.to_s+"_fields"
    options[:f] ||= :f

    tmpl = content_tag(:div,:id =>"#{options[:template]}") do
      tmpl = f.fields_for(association,options[:object], :child_index => "new_#{association}") do |b|
        render(:partial=>options[:partial],:locals =>{:f => b})
      end
    end
    tmpl = tmpl.gsub /(?<!\n)\n(?!\n)/, ' '
    tmpl = tmpl.gsub "'", "\""
    return "<script> var #{options[:template]} = '#{tmpl.to_s}' </script>".html_safe
  end

  def add_child_button(name, association,target)
    content_tag(:span,"<span>#{name}</span>".html_safe,
      :class => "add_child",
      :style => "cursor:pointer; border:1px solid #777;",
      :"data-association" => association,
      :target => target)
  end

  def remove_child_button(name)
    content_tag(:div,"<span>Remove</span>".html_safe,
      :class => "remove_child")
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/new.html.haml
%h1 Contact Datil Dave

.form
  = form_for @message, :url => create_contact_path do |f|
    .field
      = f.label :name
      %br
      = f.text_field :name

    .field
      = f.label :email
      %br
      = f.text_field :email

    .field
      = f.label :subject
      %br
      = f.text_field :subject

    .field
      = f.label :body
      %br
      = f.text_area :body

    .action
      = f.submit "Send"

app/views/contact/new_message.html.haml
%p
  Name:
  = @message.name

%p
  Email:
  = @message.email

%p
  Subject:
  = @message.subject

%p
  Body:
  = @message.body

app/views/contact/new_order.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8"}

  %body
    %p Someone just placed an order on datildave.com!
    %p Here are the details:

    %p 
      Shipping Address:
      %br

      = "#{@order.customer_first_name} #{@order.customer_last_name}"
      %br
      = @order.address_street_1
      %br

      -if @order.address_street_2
        = @order.address_street_2
        %br

      = "#{@order.address_city}, #{@order.address_state} #{@order.address_zip}"

    %p
      Order Details:
      %br
    %table
      %tr
        %th Item
        %th Price
        %th Qty
        %th Subtotal
      - Order.unpack_products(@order.products).each do |product|
        %tr
          %td= product[:product_name]
          %td= number_to_currency(product[:product_price].to_f)
          %td= product[:product_quantity]
          %td= number_to_currency(product[:product_price].to_f * product[:product_quantity].to_i)
    %p= "Subtotal: #{number_to_currency(@order.subtotal)}"
    %p= "Shipping: #{number_to_currency(@order.shipping)}"
    %p= "Total: #{number_to_currency(@order.total)}"

app/views/contact/new_order_confirmation.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8"}

  %body
    %p= "Dear #{@order.customer_first_name} #{@order.customer_last_name},"
    %p Thank you for your order with DatilDave.com. This e-mail is to confirm your order and shipping address. Please keep this for your own records.

    %p 
      Shipping Address:
      %br

      = "#{@order.customer_first_name} #{@order.customer_last_name}"
      %br
      = @order.address_street_1
      %br

    -if @order.address_street_2
      = @order.address_street_2
      %br

    = "#{@order.address_city}, #{@order.address_state} #{@order.address_zip}"

    %p Your order:
    %br
    %table
      %tr
        %th Item
        %th Price
        %th Qty
        %th Subtotal
      - Order.unpack_products(@order.products).each do |product|
        %tr
          %td= product[:product_name]
          %td= number_to_currency(product[:product_price].to_f)
          %td= product[:product_quantity]
          %td= number_to_currency(product[:product_price].to_f * product[:product_quantity].to_i)
    %p= "Subtotal: #{number_to_currency(@order.subtotal)}"
    %p= "Shipping: #{number_to_currency(@order.shipping)}"
    %p= "Total: #{number_to_currency(@order.total)}"

    %p If you have any questions or concerns, please contact us at dave@datildave.com. Thank you for your support!

    %p 
      Sincerely,
      %br
      Datil Dave