config/routes.rb
Datildave::Application.routes.draw do
  
  get 'recipes/new'

  get 'recipes/edit'

  post "product/add_to_cart" => "products#add_to_cart"
  post "cart/empty_cart" => "cart#empty_cart"
  post "order/payment" => "orders#payment"
  get "cart" => "cart#show", as: "cart"
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "contact" => "contact#new", as: :new_contact
  post "contact" => "contact#create", as: :create_contact
  match 'heartbeat', to: proc { [200, {}, ''.chars] }, via: [:get, :post]
  root to: 'home#index'

  resources :sessions
  resources :users
  resources :products
  resources :pages, only: [:new, :create, :index]
  resources :posts
  resources :orders
  resources :categories
  resources :recipes do
    resources :ingredients
  end

  #keep these at the bottom of your file. They should be the last routes.
  get "/:slug", to: "pages#show", as: :slug
  get "/:slug/edit", to: "pages#edit", as: :edit_slug
  put "/:slug", to: "pages#update", as: :update_slug
  delete "/:slug", to: "pages#destroy", as: :destroy_slug

end

app/models/cart.rb
class Cart

  def self.subtotal(args)
    sub = 0
    args.each do |item|
      sub += item[:product_price].to_f * item[:product_quantity].to_f
    end
    return sub
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many(:products)
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/message.rb
class Message
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessor :stripe_card_token

  validates_presence_of :customer_email, :address_street_1, :address_city, :address_state, :address_zip
  validates_format_of :customer_email, with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  def save_with_payment
    if valid?
      total = (100 * (shipping.to_f + subtotal.to_f)).to_i
      payment_response = Stripe::Charge.create(
        amount: total,
        currency: "usd",
        card: stripe_card_token,
        description: "Charge for #{customer_email}"
      )

      self.stripe_payment_token = payment_response.id
      save!
    end

  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while processing payment: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
  end

  def self.package_products(products)
    tmp = []
    products.each do |item|
      tmp << hash_to_string(item)
    end

    tmp.join("|")
  end

  def self.unpack_products(products)
    tmp = []
    products.split("|").each do |item|
      tmp << string_to_hash(item)
    end

    tmp
  end

  def total
    subtotal.to_f + shipping.to_f
  end

  private
  
  def self.hash_to_string(hsh)
    tst = []
    hsh.each do |key, value| 
      tst << "#{value}@#{key}"
    end

    tst.join(",")
  end

  def self.string_to_hash(str)
    hsh = str.split(",").inject(Hash.new{|h,k| h[k]=""}) do |h,s|
      v, k = s.split(/@/)
      k = k.to_sym
      h[k] = v
      h
    end
  end

end

app/models/page.rb
class Page < ActiveRecord::Base

  default_scope { order('created_at DESC, updated_at DESC') }

  validates_uniqueness_of :name

  before_save :update_slug

  def update_slug
    self.slug = name.parameterize
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :category
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: lambda { |a| a[:name].blank? }, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :name

  def self.authenticate (name, password)
    user = find_by_name(name)

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} &#215
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Datil Dave", root_path, class: 'brand'
%ul.nav.nav-tabs
  %li
    = link_to "Products", products_path
  - pages.each do |page|
    %li= link_to page.name, "/#{page.name.downcase}/"
  %li
    =link_to "Contact", "/contact/"
  %li
    = link_to "News", posts_path
  %li
    = link_to "Cart", "/cart/"
  - if current_user
    %li
      = link_to "Log Out", "/log_out"
    %li
      = link_to "New Page", new_page_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    / [if IE]
      %meta{"http-equiv" => "X-UA-Compatible", content: "IE=Edge,chrome=1"}
    
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Datil Dave"
    %meta{content: "Datil Dave E-Commerce Site", name: "description"}
    %meta{content: "Dan Bearl", name: "author"}
    = stylesheet_link_tag "bootstrap.min", media: "all"
    = stylesheet_link_tag "/font-awesome/css/font-awesome.min", media: "all"
    = stylesheet_link_tag "style", media: "all"
    = stylesheet_link_tag "responsive", media: "all"
    = javascript_include_tag "https://js.stripe.com/v1/", "application"
    = csrf_meta_tags

    / Google Web Fonts
    %link{href: "http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", rel: "stylesheet", type: "text/css"}

    / CSS Files
    //%link{href: "font-awesome/css/font-awesome.min.css", rel: "stylesheet"}
    //%link{href: "css/style.css", rel: "stylesheet"}
    //%link{href: "css/responsive.css", rel: "stylesheet"}

    / [if lt IE 9]
      %meta{"http-equiv" => "X-UA-Compatible", content: "IE=Edge,chrome=1"}
      %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{src: 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js'}

    %link{rel: "apple-touch-icon-precomposed", sizes: "144x144", href: "images/fav-144.png"}
    %link{rel: "apple-touch-icon-precomposed", sizes: "114x114", href: "images/fav-114.png"}
    %link{rel: "apple-touch-icon-precomposed", sizes: "72x72", href: "images/fav-72.png"}
    %link{rel: "apple-touch-icon-precomposed", href: "images/fav-57.png"}
    %link{rel: "shortcut icon", href: "/images/fav.png"}
    = tag :meta, name: "stripe-key", content: STRIPE_PUBLIC_KEY
    = yield(:head)

  %body
    %header#header-area
      %div.container
        /Main Header Starts
        %div.main-header
          -[:notice, :error, :alert].each do |level|
            - unless flash[level].blank?
              %div{class: "alert alert-#{flash_class(level)}"}
                %a{ href: "#", class: "close", data: { dismiss: "alert" } } &times;
                = flash[level]

          %div.row
            /Logo Starts
            %div.col-md-9
              %div#logo
                =link_to image_tag( "logo.png", title: "Datil Dave Pepper Products", alt: "Spice Shoppe", class: "img-responsive"), root_path
            /Shopping Cart Starts
            %div.col-md-3
              %div#cart.btn-group.btn-block
                %a{href: "/cart"}
                  %button{type: "button", "data-toggle" => "dropdown-menu", class: "btn btn-block btn-lg dropdown-toggle"}
                    %i.fa.fa-shopping-cart
                    %span.hidden-md
                      Cart:
                    %span#cart-total
                      -if session.has_key?(:cart)
                        = "#{session[:cart].count} item(s) - #{number_to_currency(Cart.subtotal(session[:cart]).to_f)}"
                      -else
                        0 item(s) - $0.00
                  %ul.dropdown-menu.pull-right
                    -if session.has_key?(:cart)
                      %li
                        %table.table.table-striped.hcart
                          - session[:cart].each do |item|
                            %tr
                              %td.text-left
                                =item[:product_name]
                              %td.text-right= "x #{item[:product_quantity]}"
                              %td.text-right= number_to_currency(item[:product_price])
                      %li
                        %table.table.table-bordered.total
                          %tbody
                            %tr
                              %td.text-right
                                %strong Sub-Total
                              %td.text-left= number_to_currency(Cart.subtotal(session[:cart]).to_f)
                        %p.text-right.btn-block1
                          %a{href: "/cart"} View Cart
                          %a{href: "#"}Checkout
        / Main Menu Starts
        -if current_user
          %div#admin-nav.navbar
            %ul.nav.navbar-nav
              %li
                =link_to "New Category", new_category_path
              %li
                =link_to "New Product", new_product_path
              %li
                =link_to "Orders", orders_path
              %li
                =link_to "Log Out", "/log_out"
              %li
                =link_to "Pages", pages_path
              %li
                =link_to "New Page", new_page_path
              %li
                =link_to "New Recipe", new_recipe_path
        %nav#main-menu.navbar{role: "navigation"}
          / Nav Header Starts
          %div.navbar-header
            %button{type: "button", class: "btn btn-navbar navbar-toggle", "data-toggle" => "collapse", "data-target" => ".navbar-cat-collapse"}
              %span.sr-only Toggle Navigation
              %i.fa.fa-bars
          /Navbar Cat collapse Starts
          %div.collapse.navbar-collapse.navbar-cat-collapse
            %ul.nav.navbar-nav
              -categories.each do |category|
                %li
                  =link_to category.name, category
              %li
                =link_to "Recipes", recipes_path
              -featured_pages.each do |page|
                %li= link_to page.name, slug_path(page.slug)

    %div#main-container.container
      = yield

    %footer#footer-area
      %div.footer-links
        %div.container
          %div.col-md-2.col-sm-6
            %h5 Information
            %ul
              %li
                =link_to "About Us", "/about"
              %li
                =link_to "Delivery Information", "/delivery"
              -# %li
              -#   =link_to "Privacy Policy", "/privacy"
              -# %li
              -#   =link_to "Terms & Conditions", "/terms"
          %div.col-md-2.col-sm-6
            %h5 Service
            %ul
              %li
                =link_to "Contact Us", "/contact"
          %div.col-md-2.col-sm-6
            %h5 Follow Us
            %ul
              %li
                =link_to "Facebook", "https://www.facebook.com/pages/Datil-Dave/829884310389179?ref=br_tf"
          %div.col-md-4.col-sm-12.last
            %h5 Contact Us
            %ul
              %li Datil Dave
              %li
                Email: 
                =mail_to "dave@datildave.com"
            %h4.lead
              Tel: 
              %span (904) 540-1051
    %div.copyright
      %div.container
        %p.pull-left
          &copy; 2014 Datil Dave.
        %ul.pull-right.list-inline
          %li
            =image_tag "/images/payment-icon/visa.png", alt: "PaymentGateway"
          %li
            =image_tag "/images/payment-icon/mastercard.png", alt: "PaymentGateway"
          %li
            =image_tag "/images/payment-icon/americanexpress.png", alt: "PaymentGateway"